name: dfurr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75260f'
    - '#070b0a'
    - '#a16050'
    - '#8eb8bb'
    - '#1e6069'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
